version: '2'
services:
  #  The Application
  app:
    image: howapped/yojoe
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
