version: '2'
services:
  #  The Application
  app:
    image: howapped/yojoe-app
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
  # The Web Server
  web:
    image: howapped/yojoe-web
    ports:
      - 80:80
      - 443:443
  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:
